services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql_db
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      PGPORT: ${MYSQL_PORT}
    ports:
      - "${HOST_PORT}:${MYSQL_PORT}"
    expose:
      - "${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql/data
    restart: unless-stopped

volumes:
  mysql_data:
    name: mysql_data