services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      
    ports:
      - "${HOST_PORT}:${MYSQL_PORT}"
    expose:
      - "${MYSQL_PORT}"
    command: --max_allowed_packet=256M
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
    name: mysql_data